[2022-07-22 13:00:40,079] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-22 13:00:40,123] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-22 13:00:40,126] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:40,128] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:40,133] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:40,221] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t2> on 2022-07-20 00:00:00+00:00
[2022-07-22 13:00:40,233] {standard_task_runner.py:52} INFO - Started process 918 to run task
[2022-07-22 13:00:40,251] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't2', 'scheduled__2022-07-20T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpare07zun', '--error-file', '/tmp/tmpont7aa14']
[2022-07-22 13:00:40,259] {standard_task_runner.py:80} INFO - Job 101: Subtask t2
[2022-07-22 13:00:40,372] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:40,563] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:40,771] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-20T00:00:00+00:00
[2022-07-22 13:00:40,775] {python.py:173} INFO - Done. Returned value was: goodbye
[2022-07-22 13:00:40,834] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t2, execution_date=20220720T000000, start_date=20220722T130040, end_date=20220722T130040
[2022-07-22 13:00:40,901] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:40,983] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:22,000] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-25 09:18:22,028] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-25 09:18:22,029] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:22,030] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:22,030] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:22,065] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t2> on 2022-07-20 00:00:00+00:00
[2022-07-25 09:18:22,074] {standard_task_runner.py:52} INFO - Started process 869 to run task
[2022-07-25 09:18:22,095] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't2', 'scheduled__2022-07-20T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpqqbgkvwf', '--error-file', '/tmp/tmpg1ycdyyz']
[2022-07-25 09:18:22,104] {standard_task_runner.py:80} INFO - Job 100: Subtask t2
[2022-07-25 09:18:22,154] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:22,270] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:22,455] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-20T00:00:00+00:00
[2022-07-25 09:18:22,459] {python.py:173} INFO - Done. Returned value was: goodbye
[2022-07-25 09:18:22,539] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t2, execution_date=20220720T000000, start_date=20220725T091822, end_date=20220725T091822
[2022-07-25 09:18:22,575] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:22,640] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 12:28:28,276] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-25 12:28:28,340] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [queued]>
[2022-07-25 12:28:28,342] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 12:28:28,344] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 12:28:28,345] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 12:28:28,390] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t2> on 2022-07-20 00:00:00+00:00
[2022-07-25 12:28:28,401] {standard_task_runner.py:52} INFO - Started process 1027 to run task
[2022-07-25 12:28:28,413] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't2', 'scheduled__2022-07-20T00:00:00+00:00', '--job-id', '173', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmps2yw4v38', '--error-file', '/tmp/tmpvcalnj7g']
[2022-07-25 12:28:28,420] {standard_task_runner.py:80} INFO - Job 173: Subtask t2
[2022-07-25 12:28:28,458] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 12:28:28,586] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t2 scheduled__2022-07-20T00:00:00+00:00 [running]> on host 929e6a3728d4
[2022-07-25 12:28:28,835] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-20T00:00:00+00:00
[2022-07-25 12:28:28,839] {python.py:173} INFO - Done. Returned value was: goodbye
[2022-07-25 12:28:28,924] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t2, execution_date=20220720T000000, start_date=20220725T122828, end_date=20220725T122828
[2022-07-25 12:28:28,986] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 12:28:29,202] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
