[2022-07-22 13:00:04,959] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-07-22 13:00:05,093] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-07-22 13:00:05,099] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:05,106] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:05,127] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:05,313] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-06-17 00:00:00+00:00
[2022-07-22 13:00:05,354] {standard_task_runner.py:52} INFO - Started process 774 to run task
[2022-07-22 13:00:05,423] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-06-17T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmplxe3u_e2', '--error-file', '/tmp/tmps3mkdoni']
[2022-07-22 13:00:05,439] {standard_task_runner.py:80} INFO - Job 34: Subtask t1
[2022-07-22 13:00:05,646] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:06,916] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-06-17T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:09,947] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T00:00:00+00:00
[2022-07-22 13:00:09,963] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-22 13:00:11,030] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220617T000000, start_date=20220722T130004, end_date=20220722T130011
[2022-07-22 13:00:11,543] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:12,482] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:00,909] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-07-25 09:18:00,924] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-06-17T00:00:00+00:00 [queued]>
[2022-07-25 09:18:00,925] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:00,926] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:00,927] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:00,958] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-06-17 00:00:00+00:00
[2022-07-25 09:18:00,965] {standard_task_runner.py:52} INFO - Started process 726 to run task
[2022-07-25 09:18:00,970] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-06-17T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpmyfwx6dy', '--error-file', '/tmp/tmpvioqir1x']
[2022-07-25 09:18:00,975] {standard_task_runner.py:80} INFO - Job 34: Subtask t1
[2022-07-25 09:18:01,021] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:01,163] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-06-17T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:01,372] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-17T00:00:00+00:00
[2022-07-25 09:18:01,381] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-25 09:18:01,506] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220617T000000, start_date=20220725T091800, end_date=20220725T091801
[2022-07-25 09:18:01,553] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:01,785] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
