[2022-07-22 13:00:27,135] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-06T00:00:00+00:00 [queued]>
[2022-07-22 13:00:27,225] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-06T00:00:00+00:00 [queued]>
[2022-07-22 13:00:27,232] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:27,235] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:27,236] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:27,344] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-06 00:00:00+00:00
[2022-07-22 13:00:27,358] {standard_task_runner.py:52} INFO - Started process 839 to run task
[2022-07-22 13:00:27,370] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-06T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpavit4buf', '--error-file', '/tmp/tmpe4jpz04d']
[2022-07-22 13:00:27,377] {standard_task_runner.py:80} INFO - Job 65: Subtask t1
[2022-07-22 13:00:27,461] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:27,761] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-06T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:28,241] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-06T00:00:00+00:00
[2022-07-22 13:00:28,246] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-22 13:00:28,422] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220706T000000, start_date=20220722T130027, end_date=20220722T130028
[2022-07-22 13:00:28,544] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:29,070] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:09,837] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-06T00:00:00+00:00 [queued]>
[2022-07-25 09:18:09,868] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-06T00:00:00+00:00 [queued]>
[2022-07-25 09:18:09,902] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:09,910] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:09,911] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:10,010] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-06 00:00:00+00:00
[2022-07-25 09:18:10,021] {standard_task_runner.py:52} INFO - Started process 802 to run task
[2022-07-25 09:18:10,050] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-06T00:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpag_39wep', '--error-file', '/tmp/tmp4_d7gueq']
[2022-07-25 09:18:10,053] {standard_task_runner.py:80} INFO - Job 66: Subtask t1
[2022-07-25 09:18:10,097] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:10,252] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-06T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:10,646] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-06T00:00:00+00:00
[2022-07-25 09:18:10,650] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-25 09:18:10,758] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220706T000000, start_date=20220725T091809, end_date=20220725T091810
[2022-07-25 09:18:10,877] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:11,057] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
