[2022-07-22 13:00:25,582] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-01T00:00:00+00:00 [queued]>
[2022-07-22 13:00:25,605] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-01T00:00:00+00:00 [queued]>
[2022-07-22 13:00:25,606] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:25,607] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:25,608] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:25,652] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-01 00:00:00+00:00
[2022-07-22 13:00:25,660] {standard_task_runner.py:52} INFO - Started process 827 to run task
[2022-07-22 13:00:25,675] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-01T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpkj_xtnsu', '--error-file', '/tmp/tmp0rvtap2q']
[2022-07-22 13:00:25,679] {standard_task_runner.py:80} INFO - Job 60: Subtask t1
[2022-07-22 13:00:25,732] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:25,930] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-01T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:26,186] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-01T00:00:00+00:00
[2022-07-22 13:00:26,189] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-22 13:00:26,411] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220701T000000, start_date=20220722T130025, end_date=20220722T130026
[2022-07-22 13:00:26,493] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:26,800] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:08,528] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-01T00:00:00+00:00 [queued]>
[2022-07-25 09:18:08,571] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-01T00:00:00+00:00 [queued]>
[2022-07-25 09:18:08,573] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:08,576] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:08,583] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:08,654] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-01 00:00:00+00:00
[2022-07-25 09:18:08,668] {standard_task_runner.py:52} INFO - Started process 790 to run task
[2022-07-25 09:18:08,688] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-01T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpily78k3o', '--error-file', '/tmp/tmpdlr8otxh']
[2022-07-25 09:18:08,692] {standard_task_runner.py:80} INFO - Job 61: Subtask t1
[2022-07-25 09:18:08,751] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:08,959] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-01T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:09,160] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-01T00:00:00+00:00
[2022-07-25 09:18:09,162] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-25 09:18:09,283] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220701T000000, start_date=20220725T091808, end_date=20220725T091809
[2022-07-25 09:18:09,378] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:09,566] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
