[2022-07-22 13:00:25,753] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2022-07-22 13:00:25,786] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2022-07-22 13:00:25,787] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:25,791] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:25,791] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:25,856] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-02 00:00:00+00:00
[2022-07-22 13:00:25,869] {standard_task_runner.py:52} INFO - Started process 829 to run task
[2022-07-22 13:00:25,886] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-02T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpzfxkq0nj', '--error-file', '/tmp/tmpjapchtjz']
[2022-07-22 13:00:25,892] {standard_task_runner.py:80} INFO - Job 61: Subtask t1
[2022-07-22 13:00:25,962] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:26,139] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-02T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:26,490] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T00:00:00+00:00
[2022-07-22 13:00:26,492] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-22 13:00:26,720] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220702T000000, start_date=20220722T130025, end_date=20220722T130026
[2022-07-22 13:00:26,826] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:27,082] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:08,833] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2022-07-25 09:18:08,868] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2022-07-25 09:18:08,890] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:08,891] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:08,892] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:08,922] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-02 00:00:00+00:00
[2022-07-25 09:18:08,932] {standard_task_runner.py:52} INFO - Started process 792 to run task
[2022-07-25 09:18:08,946] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-02T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpwe9_bluq', '--error-file', '/tmp/tmpldiz8u6h']
[2022-07-25 09:18:08,948] {standard_task_runner.py:80} INFO - Job 62: Subtask t1
[2022-07-25 09:18:09,013] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:09,222] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-02T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:09,481] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-02T00:00:00+00:00
[2022-07-25 09:18:09,484] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-25 09:18:09,612] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220702T000000, start_date=20220725T091808, end_date=20220725T091809
[2022-07-25 09:18:09,719] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:09,904] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
