[2022-07-22 13:00:35,335] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-17T00:00:00+00:00 [queued]>
[2022-07-22 13:00:35,389] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-17T00:00:00+00:00 [queued]>
[2022-07-22 13:00:35,395] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:35,396] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:35,397] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:35,468] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-17 00:00:00+00:00
[2022-07-22 13:00:35,486] {standard_task_runner.py:52} INFO - Started process 894 to run task
[2022-07-22 13:00:35,492] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-17T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpeg799k46', '--error-file', '/tmp/tmpcec8h009']
[2022-07-22 13:00:35,497] {standard_task_runner.py:80} INFO - Job 89: Subtask t1
[2022-07-22 13:00:35,540] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:35,791] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-17T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:36,156] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-17T00:00:00+00:00
[2022-07-22 13:00:36,161] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-22 13:00:36,330] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220717T000000, start_date=20220722T130035, end_date=20220722T130036
[2022-07-22 13:00:36,444] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:36,801] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:19,260] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-17T00:00:00+00:00 [queued]>
[2022-07-25 09:18:19,344] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t1 scheduled__2022-07-17T00:00:00+00:00 [queued]>
[2022-07-25 09:18:19,345] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:19,346] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:19,347] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:19,462] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t1> on 2022-07-17 00:00:00+00:00
[2022-07-25 09:18:19,477] {standard_task_runner.py:52} INFO - Started process 849 to run task
[2022-07-25 09:18:19,495] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't1', 'scheduled__2022-07-17T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpyw6d7ksm', '--error-file', '/tmp/tmpdrb6kbyl']
[2022-07-25 09:18:19,507] {standard_task_runner.py:80} INFO - Job 91: Subtask t1
[2022-07-25 09:18:19,572] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:19,873] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t1 scheduled__2022-07-17T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:20,241] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-07-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-17T00:00:00+00:00
[2022-07-25 09:18:20,244] {python.py:173} INFO - Done. Returned value was: welcome
[2022-07-25 09:18:20,365] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t1, execution_date=20220717T000000, start_date=20220725T091819, end_date=20220725T091820
[2022-07-25 09:18:20,486] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:20,700] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
