[2022-07-22 13:00:38,052] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-22 13:00:38,145] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-22 13:00:38,148] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:38,151] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-22 13:00:38,153] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-22 13:00:38,232] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t2> on 2022-07-18 00:00:00+00:00
[2022-07-22 13:00:38,248] {standard_task_runner.py:52} INFO - Started process 913 to run task
[2022-07-22 13:00:38,267] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't2', 'scheduled__2022-07-18T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpj_nt8j6u', '--error-file', '/tmp/tmp264gx5nd']
[2022-07-22 13:00:38,270] {standard_task_runner.py:80} INFO - Job 99: Subtask t2
[2022-07-22 13:00:38,357] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-22 13:00:38,531] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [running]> on host 2f63307804d5
[2022-07-22 13:00:38,914] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T00:00:00+00:00
[2022-07-22 13:00:38,917] {python.py:173} INFO - Done. Returned value was: goodbye
[2022-07-22 13:00:39,152] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t2, execution_date=20220718T000000, start_date=20220722T130038, end_date=20220722T130039
[2022-07-22 13:00:39,208] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-22 13:00:39,419] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 09:18:21,992] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-25 09:18:22,016] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-25 09:18:22,017] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:22,020] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 09:18:22,021] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 09:18:22,056] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t2> on 2022-07-18 00:00:00+00:00
[2022-07-25 09:18:22,066] {standard_task_runner.py:52} INFO - Started process 868 to run task
[2022-07-25 09:18:22,090] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't2', 'scheduled__2022-07-18T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmp4_w43i2q', '--error-file', '/tmp/tmpg2s62hhm']
[2022-07-25 09:18:22,097] {standard_task_runner.py:80} INFO - Job 99: Subtask t2
[2022-07-25 09:18:22,143] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 09:18:22,302] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [running]> on host 01e6b1df1873
[2022-07-25 09:18:22,533] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T00:00:00+00:00
[2022-07-25 09:18:22,535] {python.py:173} INFO - Done. Returned value was: goodbye
[2022-07-25 09:18:22,597] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t2, execution_date=20220718T000000, start_date=20220725T091821, end_date=20220725T091822
[2022-07-25 09:18:22,652] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 09:18:22,726] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-07-25 12:28:28,429] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-25 12:28:28,493] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [queued]>
[2022-07-25 12:28:28,494] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 12:28:28,495] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-25 12:28:28,496] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-25 12:28:28,597] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): t2> on 2022-07-18 00:00:00+00:00
[2022-07-25 12:28:28,617] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 't2', 'scheduled__2022-07-18T00:00:00+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/nickdag.py', '--cfg-path', '/tmp/tmpfzwwtbpp', '--error-file', '/tmp/tmpr21ovx0f']
[2022-07-25 12:28:28,623] {standard_task_runner.py:80} INFO - Job 174: Subtask t2
[2022-07-25 12:28:28,619] {standard_task_runner.py:52} INFO - Started process 1035 to run task
[2022-07-25 12:28:28,693] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:528 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-25 12:28:28,900] {task_command.py:371} INFO - Running <TaskInstance: tutorial.t2 scheduled__2022-07-18T00:00:00+00:00 [running]> on host 929e6a3728d4
[2022-07-25 12:28:29,484] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=caroline.kosalka@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2022-07-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-18T00:00:00+00:00
[2022-07-25 12:28:29,486] {python.py:173} INFO - Done. Returned value was: goodbye
[2022-07-25 12:28:29,912] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=t2, execution_date=20220718T000000, start_date=20220725T122828, end_date=20220725T122829
[2022-07-25 12:28:29,983] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-25 12:28:30,251] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
